# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Java CI

on:
  push:
    branches: [ xenoamess_maintain_fork ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ windows-latest , ubuntu-latest , macos-latest ]
        java: [ 21 ]
        experimental: [ false ]

    steps:
      - uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-gradle-m2-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v6
        with:
          path: ~/.gradle/caches/
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v6
        with:
          path: ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v6.0.1
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Build Build Build!
        run: |
          cd ./p3c-pmd
          chmod 777 ./mvnw
          ./mvnw install -Penforce
          cd ../
          cd ./idea-plugin
          chmod 777 ./gradlew
          ./gradlew buildPlugin -s

      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v7
        with:
          name: p3c-idea-plugin-${{ matrix.os }}-${{ matrix.java }}
          path: idea-plugin/p3c-idea/build/distributions/*.zip
          if-no-files-found: warn